services:
  nginx:
    image: nginx:latest
    container_name: lemp-webserver
    restart: always
    links:
      - php
      - db
    volumes:
      - ./app:/var/www/app:ro
      - ${CUSTOM_APP_DIR}:/var/www/app/web:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80

  php:
    image: ewan1011/php:latest
    container_name: lemp-php
    restart: always
    volumes:
      - ./app:/var/www/app
      - ${CUSTOM_APP_DIR}:/var/www/app/web
    environment:
      PMA_PORT: 8080
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: user
      MARIADB_PASSWORD: 1234
      MARIADB_DATABASE: docker
    depends_on:
      - db
    links:
      - db
    ports:
      - 9000:9000

  db:
    image: mariadb:latest
    container_name: lemp-mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: user
      MARIADB_PASSWORD: 1234
      MARIADB_DATABASE: docker
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: lemp-phpmyadmin
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - db
    links:
      - db

volumes:
  db-data:
